/**
 * Quanti Mock Harness — auto-generated by `quanti dev`
 * DO NOT EDIT — this file is regenerated on every `quanti dev` run.
 */
import React, { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { MediaTestTable, MediaTestDetailPanel, MediaTestDashboardWidget } from '@components/index';

const MOCK_CONTEXT = {
  projectId:   1,
  instanceKey: 'default',
  lang:        'en',
  moduleId:    'quanti-module-media-test',
};

function Topbar() {
  return (
    <div style={{ height: 44, borderBottom: '1px solid #e5e7eb', display: 'flex',
                   alignItems: 'center', padding: '0 16px', gap: 12,
                   background: '#fff', fontFamily: 'Inter, sans-serif' }}>
      <span style={{ fontWeight: 600, fontSize: 14 }}>▤ Quanti Mock Harness</span>
      <span style={{ marginLeft: 'auto', fontSize: 12, color: '#6b7280' }}>
        Module: media-test v1.0.0
      </span>
    </div>
  );
}

function MockSidebar() {
  return (
    <div style={{ width: 224, borderRight: '1px solid #e5e7eb', padding: '12px 0',
                   background: '#fafafa', fontSize: 13, fontFamily: 'Inter, sans-serif' }}>
      <div style={{ padding: '6px 16px', borderLeft: '4px solid #0051C3',
                    background: 'rgba(0, 81, 195, 0.05)', fontWeight: 500 }}>
        quanti-module-media-test
      </div>
    </div>
  );
}

function SlotContainer({ name, children }: { name: string; children: React.ReactNode }) {
  return (
    <div style={{ border: '1px dashed #d1d5db', borderRadius: 6, padding: 16, marginBottom: 16 }}>
      <div style={{ fontSize: 10, fontWeight: 600, textTransform: 'uppercase',
                    color: '#9ca3af', marginBottom: 8, letterSpacing: '0.05em' }}>
        Slot: {name}
      </div>
      {children}
    </div>
  );
}

function MockContextSidebar() {
  return (
    <div style={{ width: 280, borderLeft: '1px solid #e5e7eb', display: 'flex',
                   flexDirection: 'column', fontSize: 13, fontFamily: 'Inter, sans-serif' }}>
      <div style={{ height: 44, borderBottom: '1px solid #e5e7eb', display: 'flex',
                     alignItems: 'center', padding: '0 16px', fontWeight: 500 }}>
        quanti-module-media-test Tools
      </div>

    </div>
  );
}

function DevDock() {
  const [tab, setTab] = useState<'context' | 'events'>('context');
  const [events, setEvents] = useState<Array<{ type: string; detail: unknown; timestamp: number }>>([]);

  useEffect(() => {
    const handler = (e: Event) => {
      const ce = e as CustomEvent;
      setEvents(prev => [...prev, { type: ce.type, detail: ce.detail, timestamp: Date.now() }]);
    };
    const names = ['quanti:sidebar:open', 'quanti:sidebar:close', 'quanti:navigation:update'];
    names.forEach(name => window.addEventListener(name, handler));
    return () => names.forEach(name => window.removeEventListener(name, handler));
  }, []);

  return (
    <div style={{ height: 160, borderTop: '1px solid #e5e7eb', background: '#1e1e1e',
                   color: '#d4d4d4', fontFamily: 'monospace', fontSize: 12, padding: 8 }}>
      <div style={{ display: 'flex', gap: 12, marginBottom: 8 }}>
        <button onClick={() => setTab('context')}
                style={{ color: tab === 'context' ? '#60a5fa' : '#9ca3af',
                         background: 'none', border: 'none', cursor: 'pointer', fontSize: 11 }}>
          Context Inspector
        </button>
        <button onClick={() => setTab('events')}
                style={{ color: tab === 'events' ? '#60a5fa' : '#9ca3af',
                         background: 'none', border: 'none', cursor: 'pointer', fontSize: 11 }}>
          Event Log
        </button>
      </div>
      {tab === 'context' && <pre>{JSON.stringify(MOCK_CONTEXT, null, 2)}</pre>}
      {tab === 'events' && (
        events.length === 0
          ? <div style={{ color: '#6b7280' }}>Listening for quanti:* events…</div>
          : events.map((ev, i) => (
              <div key={i}>[{new Date(ev.timestamp).toISOString()}] {ev.type}</div>
            ))
      )}
    </div>
  );
}

function App() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh',
                   fontFamily: 'Inter, sans-serif' }}>
      <Topbar />
      <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
        <MockSidebar />
        <div style={{ flex: 1, padding: 24, overflow: 'auto', background: '#f9fafb' }}>
    <SlotContainer name="media_test_main_view"><MediaTestTable context={MOCK_CONTEXT} /></SlotContainer>
    <SlotContainer name="media_test_detail_panel"><MediaTestDetailPanel context={MOCK_CONTEXT} /></SlotContainer>
    <SlotContainer name="dashboard_widget"><MediaTestDashboardWidget context={MOCK_CONTEXT} /></SlotContainer>
        </div>
        <MockContextSidebar />
      </div>
      <DevDock />
    </div>
  );
}

createRoot(document.getElementById('root')!).render(<App />);
