// @vitest-environment jsdom
/**
 * MediaTestTable — Unit Tests
 *
 * TDD seed: tests generated by `quanti create`.
 * Run with: npm run test
 *
 * Rules (TESTING_STANDARDS.md):
 *   - Test via component props (black-box)
 *   - No excessive mocking — test real render output
 *   - min 2 sad paths per happy path
 */

import { describe, it, expect, afterEach } from 'vitest';
import { render, screen, cleanup } from '@testing-library/react';
import { MediaTestTable } from './MediaTestTable';

describe('MediaTestTable', () => {
    afterEach(() => cleanup());

    const validContext = {
        projectId: 42,
        instanceKey: 'default',
    };

    // ── Happy path: renders without crashing ──────────────────────────────────
    it('should render with valid context', () => {
        render(<MediaTestTable context={validContext} />);
        expect(screen.getByText(/project 42/i)).toBeTruthy();
    });

    // ── Sad path: missing instanceKey defaults gracefully ─────────────────────
    it('should render when instanceKey is omitted', () => {
        const ctx = { projectId: 1 };
        render(<MediaTestTable context={ctx} />);
        expect(screen.getByText(/project 1/i)).toBeTruthy();
    });

    // ── Sad path: zero projectId renders without error ────────────────────────
    it('should handle projectId of 0', () => {
        const ctx = { projectId: 0 };
        render(<MediaTestTable context={ctx} />);
        expect(screen.getByText(/project 0/i)).toBeTruthy();
    });
});
